/*
 * File: Main.ui.js
 * Date: Tue Nov 21 2017 23:52:38 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MainUi = Ext.extend(Ext.Viewport, {
    layout: 'fit',
    style: '',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                layout: 'border',
                style: 'border-width:0px;',
                border: false,
                items: [
                    {
                        xtype: 'panel',
                        height: 75,
                        border: false,
                        hideBorders: true,
                        unstyled: true,
                        region: 'north',
                        cls: 'x-panel-mc',
                        itemId: 'pnlHeader',
                        layout: 'border',
						style: '',
                        items: [
                            {
                                xtype: 'panel',
                                region: 'east',
                                width: 200,
                                height: 45,
                                style: '',
                                items: [
                                    {
                                        xtype: 'displayfield',
                                        value: 'Sistema',
                                        width: 200,
                                        style: 'font-size: 30px;\nfont-weight:bold;\n color:#0a4661;font-family:arial;letter-spacing: 1px;margin-left:5px '
										
									}
                                ]
                            },
                            {
                                xtype: 'panel',
                                region: 'center',
								items: [
                                    
                                    {
                                        xtype: 'panel',
                                        width: 600,
                                        height: 45,
                                        style: 'float:right;margin-right:10px; ',
                                        //labelWidth: 60,
                                        items: [
                                            {
                                                xtype: 'panel',
                                                layout: 'hbox',
                                                //height: 40,
                                                items: [
                                                    
                                                    {
                                                        xtype: 'displayfield',
                                                        value: '{nombre_usuario}',
                                                        flex: 1,
                                                        style: 'float:right;font-size: 30px;\n    font-weight: bold;\nmargin-left:10px;color:#0a4661;font-family:arial;letter-spacing: 1px',
                                                        itemId: 'lblNombreUsuario',
                                                        ref: '../../../../../lblNombreUsuario',
                                                        id: 'lblNombreUsuario'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                    
                                ]
                            },
                            {
                                xtype: 'panel',
                                region: 'east',
                                width: 45,
                                style: '',
                                items: [
								
                                    {
                                        xtype: 'panel',
                                        //style: 'margin-right:2px;float:right;margin-top:0px; ',
                                        height: 45,
                                        width: 40,
										layout: 'column',
                                        items: [
											{
                                                xtype: 'panel',
                                                tpl: '\'<img src=\'../images/salir.png\' />\'',
                                                html: '<a href="logout.php" target="_self">\n<img border="0" alt="Cerrar Sesion" src="images/iconos/salir.png" width="25" height="25" >\n</a>'
                                            }
                                        ]
                                    }
                                ]
                            },
							{
								xtype: 'panel',
								region: 'south',
								height: 30 ,
								unstyled: true,
								layout: 'fit',
								items:[
									{
										xtype: 'toolbar',
										//width: 600,
										//height: 100,
										items: [
											{
												xtype: 'button',
												text: 'Usuarios',
												height: 25,
												width: 100,
												//cls: '',
												style: 'margin:1px 0px 1px 1px;',
												iconAlign: 'left',
												iconCls: 'icon-usuarios',
												//scale: 'large',
												itemId: 'btnUsuarios',
												ref: '../../../../btnUsuarios'      
											},
											{
												xtype: 'button',
												text: 'Clientes',
												height: 25,
												width: 100,
												//cls: '',
												style: 'margin:1px 0px 1px 1px;',
												iconAlign: 'left',
												iconCls: 'icon-clientes',
												//scale: 'large',
												itemId: 'btnClientes',
												ref: '../../../../btnClientes'
											},
											{
												xtype: 'button',
												text: 'Trabajadores',
												height: 25,
												width: 100,
												//cls: '',
												style: 'margin:1px 0px 1px 1px;',
												iconAlign: 'left',
												iconCls: 'icon-clientes',
												//scale: 'large',
												itemId: 'btnTrabajadores',
												ref: '../../../../btnTrabajadores'
											},
											{
												xtype: 'button',
												text: 'Productos',
												height: 25,
												width: 100,
												//cls: '',
												style: 'margin:1px 0px 1px 1px;',
												iconAlign: 'left',
												iconCls: 'icon-productos',
												//scale: 'large',
												itemId: 'btnProductos',
												ref: '../../../../btnProductos'
											},
											{
												xtype: 'button',
												text: 'Pedidos',
												height: 25,
												width: 100,
												//cls: '',
												style: 'margin:1px 0px 1px 1px;',
												iconAlign: 'left',
												iconCls: 'icon-pedidos',
												//scale: 'large',
												itemId: 'btnPedidos',
												ref: '../../../../btnPedidos'
											},
											{
												xtype: 'button',
												text: 'Asignacion',
												height: 25,
												width: 100,
												//cls: '',
												style: 'margin:1px 0px 1px 1px;',
												iconAlign: 'left',
												iconCls: 'icon-asignacion',
												//scale: 'large',
												itemId: 'btnAsignacion',
												ref: '../../../../btnAsignacion'
											},
											{
												xtype: 'button',
												text: 'Registros Rentas',
												height: 25,
												width: 100,
												//cls: '',
												style: 'margin:1px 0px 1px 1px;',
												iconAlign: 'left',
												iconCls: 'icon-rentas',
												//scale: 'large',
												itemId: 'btnRentas',
												ref: '../../../../btnRentas'
											},
											{
												xtype: 'button',
												text: 'Gastos',
												height: 25,
												width: 100,
												//cls: '',
												style: 'margin:1px 0px 1px 1px;',
												iconAlign: 'left',
												iconCls: 'icon-gastos',
												//scale: 'large',
												itemId: 'btnGastos',
												ref: '../../../../btnGastos'
											},
											{
												xtype: 'splitbutton',
												text: 'Reportes',
												height: 25,
												width: 100,
												//cls: '',
												style: 'margin:1px 0px 1px 1px;',
												iconAlign: 'left',
												iconCls: 'icon-reportes',
												//scale: 'large',
												itemId: 'btnReportes',
												ref: '../../../../btnReportes',
												menu:{
													items: [
														{
															text: 'Reporte de Rentas',
															itemId: 'btnReporteRentas',
															ref: '../../../../../../btnReporteRentas',
															icon: 'images/iconos/facturas.png'
															
														},
														{
															text: 'Reporte de Gastos',
															itemId: 'btnReporteGastos',
															ref: '../../../../../../btnReporteGastos',
															icon: 'images/iconos/servicios.png'
															
														},														
														{
															text: 'Reporte de Inventario',
															itemId: 'btnReporteInventario',
															ref: '../../../../../../btnReporteInventario',
															icon: 'images/iconos/wooden_box.png'
															
														}
													]
												}
											}
										]
									}
								]
							}
                        ]
                    },
                 
                    {
                        xtype: 'tabpanel',
                        activeTab: 0,
                        region: 'center',
                        itemId: 'tabContainer',
                        enableTabScroll: true,
                        ref: '../tabContainer',
                        id: 'tabContainer',
                        items: [
                            {
                                xtype: 'panel',
                                title: 'Home',
                                width: 74
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        region: 'south',
                        width: 100,
                        height: 5,
                        unstyled: true
                    }
                ]
            }
        ];
        MainUi.superclass.initComponent.call(this);
    }
});
