/*
 * File: formProductos.js
 * Date: Thu Feb 02 2017 23:47:25 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('eNuevoOriente');
formProductos = Ext.extend(formProductosUi, {
	idReg:0,
	idSeleccionado:0,
	configurarToobar:function(){
		
			this.btnAgregar.setIcon('images/iconos/productos_add.png');
			this.btnEditar.setIcon('images/iconos/productos_edit.png');
			this.btnEliminar.setIcon('images/iconos/productos_delete.png');
			
		
		
	},
	inicializarStores: function(){
		
		this.gridProducto.store=new eNuevoOriente.storeGridProducto();
		this.gridProducto.bottomToolbar.bindStore(this.gridProducto.getStore());		
		this.cmbStatus.store = new eNuevoOriente.storeStatus();        				 
		this.gridProducto.bottomToolbar.pageSize=eNuevoOriente.parametros.registros_pagina;
		
		
		
	},
	inicializarEventos: function(){
				 
		var data=new Array(
							{id:'A',nombre:eNuevoOriente.formatearTexto('ACTIVOS')},
							{id:'I',nombre:eNuevoOriente.formatearTexto('INACTIVOS')},
							{id:'T',nombre:eNuevoOriente.formatearTexto('TODOS')}
					);
			 this.cmbStatus.store.loadData({data:data});
			 this.cmbStatus.setValue(eNuevoOriente.formatearTexto('A'));	
		
		this.gridProducto.store.on('beforeload',function(){
				 
				this.gridProducto.store.baseParams=this.gridProducto.store.baseParams || {};
				this.gridProducto.store.baseParams.filtro=this.txtFiltro.getValue();
				this.gridProducto.store.baseParams.filtroStatus=this.cmbStatus.getValue();
			},this);
		
		this.gridProducto.store.on('load',function(){
			this.el.unmask();
		},this);
		
		
		this.btnGuardar.on('click', function(){
			this.guardar();		
		}, this);
		
		this.btnAgregar.on('click',function(){
			this.nuevo();
		},this);
		
		this.btnEditar.on('click',function(){
			var record = this.gridProducto.store.getAt(this.idSeleccionado);				
			this.idReg = record.data.id_producto;
			this.txtDescripcion.setValue(eNuevoOriente.formatearTexto(record.data.descripcion));
			this.txtCodigoBarras.setValue(eNuevoOriente.formatearTexto(record.data.codigo_barra));
			this.txtPrecio.setValue(eNuevoOriente.formatearTexto(record.data.precio));
			this.txtStatus.setValue(record.data.status);
			this.txtDescripcion.focus(true, 0);	
			this.btnDesactivar.setDisabled(false);
				
			
		},this);
		
		this.btnEliminar.on('click',function(){
			this.eliminar();
		},this);
		
		this.btnDesactivar.on('click',function(){	
			this.cancelar();			
		},this);
		
		this.txtFiltro.on('specialkey',function(comp,e){		
			if (e.getCharCode()==e.ENTER){
				this.gridProducto.bottomToolbar.doRefresh();
			}
		},this);
		
		this.cmbStatus.on('select',function(combo, record, index){	
				this.gridProducto.bottomToolbar.doRefresh();			
		},this);
		
		 this.gridProducto.on('rowclick', this.onRowClick, this);
		 
		 
		this.gridProducto.on('celldblclick', this.editar , this);

		this.on('cambioDeStatus',function(params){			
			var status=params.status;
			switch(status){
				case 'I':
					this.btnDesactivar.setIcon("images/iconos/productos_green.png");
					this.btnDesactivar.setText("Activar");
				break;
				case 'A':
					this.btnDesactivar.setIcon("images/iconos/productos_red.png");
					this.btnDesactivar.setText("Desactivar");
				break;
			}
		},this);		
		
	},
	initComponent: function() {
        formProductos.superclass.initComponent.call(this);
		this.gridProducto.columnaStatus="status";
		
		this.txtStatus.setValue=function(value){        	
        	Ext.form.TextField.prototype.setValue.apply(this,arguments);
        	this.fireEvent('cambioDeStatus',{status:value});
        };
		
		this.configurarToobar();
		this.inicializarStores();
		this.inicializarEventos();
		
    },
	guardar:function(){
		if (this.formProducto.getForm().isValid()){			
			var params={};			
			params['Producto[id_producto]'] = this.idReg;
			params['Producto[descripcion]'] = this.txtDescripcion.getValue();
			params['Producto[codigo_barra]'] = this.txtCodigoBarras.getValue();
			params['Producto[precio]'] = this.txtPrecio.getValue();
					
			
			this.el.mask('Guardando...');
			this.formProducto.getForm().submit({
				params:params,
				scope:this,
				url:'app.php/productos/guardar',
				success:function(){
					this.el.unmask();
					this.idReg=0;
					this.formProducto.getForm().reset();
					this.btnDesactivar.setDisabled(true);
					this.gridProducto.bottomToolbar.doRefresh();
				},
				failure:function(form, action){
					switch (action.failureType) {
		            case Ext.form.Action.CLIENT_INVALID:		                
		                msg="Favor de revisar los campos marcados";
		                icon=Ext.MessageBox.WARNING;
		                break;
		            case Ext.form.Action.CONNECT_FAILURE:		                
		                msg="Error en la comunicación ajax, intente de nuevo";
		                icon=Ext.MessageBox.ERROR;
		                break;
		            case Ext.form.Action.SERVER_INVALID:
		                icon=Ext.MessageBox.ERROR;
		                msg=action.result.msg;
					}
					Ext.Msg.show({
					   title:'Error',
					   msg: msg,
					   buttons: Ext.Msg.OK,						  						   
					   icon: icon
					});
					this.el.unmask();
					}

				});
				
			
		}else{
			return;
			
		}	
		
		
	},
	nuevo: function(){
		this.formProducto.getForm().reset();
		this.idReg = 0;
		this.txtDescripcion.focus(true);
		this.btnDesactivar.setDisabled(true);
	},
	editar: function(Grid, rowIndex, columnIndex, e){		
		var record = this.gridProducto.store.getAt(rowIndex);				
		this.idReg = record.data.id_producto;
		this.txtDescripcion.setValue(eNuevoOriente.formatearTexto(record.data.descripcion));
		this.txtCodigoBarras.setValue(eNuevoOriente.formatearTexto(record.data.codigo_barra));
		this.txtPrecio.setValue(eNuevoOriente.formatearTexto(record.data.precio));
		
		this.txtStatus.setValue(record.data.status);
		this.txtDescripcion.focus(true, 0);	
		this.btnDesactivar.setDisabled(false);
		
		
	},
	eliminar:function(btn,id){
		switch(btn){	//ESTE SWITCH ES USADO PARA ANALIZAR LO QUE TRATA DE HACER EL USUARIO, LA PRIERA VEZ DEBE ENTRAR A default:
    	case 'no':
    		return;
    	break;
    	case 'yes':
    		this.eliminar('borrar');
    		return;
    		break;
    	case 'borrar':
    		break;		//SALE DEL SWITCH Y SIGUE EJECUTANDOSE LA FUNCI�N
    	case undefined:	//AQUI ENTRA LA PRIMERA VEZ
    	case false:    		
    	default:
    		var me=this;    		
    		Ext.Msg.show({
 			   title:'Confirme por favor',
 			   msg: "¿Desea eliminar el Producto?",
 			   buttons: Ext.Msg.YESNO,
 			   fn: function(btn){	    				
    				me.eliminar(btn);
    			},
 			   scope:this,
 			   icon: Ext.MessageBox.QUESTION
 			});
    		return;
		} 
		
		if (id==undefined){	//obtener el id del registro seleccionado
    		var  sel=this.gridProducto.getSelectionModel().getSelections();
    		if (sel.length==undefined || sel.length==0){
    			return;
    		}else{
    			id=sel[0].id;    			
    		}
    	}
		
		this.el.mask(eno.mensajeDeEspera);
		Ext.Ajax.request({
			params: { id_producto: id },
			scope:this,
		   	url: 'app.php/productos/eliminar',
		   	success: function(response,options){	
				var respuesta=Ext.decode(response.responseText);
				if (respuesta.success==false){
					this.el.unmask();
					return;
				}
				this.idReg=0;
				this.formProducto.getForm().reset();
				this.btnDesactivar.setDisabled(true);
				this.gridProducto.bottomToolbar.doRefresh();			
				
		   	},
		   	failure: function(){
		   		this.el.unmask();
		   	}		   
		});
	},
	cancelar:function(){
		this.el.mask(eno.mensajeDeEspera);
		Ext.Ajax.request({
			params: { 
				id_producto: this.idReg,
				status:this.txtStatus.getValue()
			},
			scope:this,
		   	url: 'app.php/productos/cambiarstatus',
		   	success: function(response, options){
				this.el.unmask();			
				var respuesta=Ext.decode(response.responseText);
				if (respuesta.success==true){
						if (respuesta.data.status!=undefined){
							this.txtStatus.setValue(respuesta.data.status);
						}
					this.gridProducto.bottomToolbar.doRefresh();	
				}
		   	},
		   	failure: function(){
		   		this.el.unmask();
		   	}		   
		});
	},	
	onRowClick : function( grid ,rowIndex, e ){
		var  sel=this.gridProducto.getSelectionModel().getSelections();
		if (sel.length==undefined || sel.length==0){
			this.btnEditar.setDisabled(true);
		}else{
			this.btnEditar.setDisabled(false);
			this.idSeleccionado = rowIndex;
		}
		if (sel.length==undefined || sel.length==0){
			this.btnEliminar.setDisabled(true);
		}else{
			this.btnEliminar.setDisabled(false);
			this.idSeleccionado = rowIndex;
		}
		
	},
	listeners:{
		activate:function(){
			if (this.activado==true){
				return;
			}
			this.activado=true;
			this.gridProducto.bottomToolbar.doRefresh();
		}   	
    }
	
});
Ext.reg('formProductos', formProductos);
