/*
 * File: eNuevoOriente.storeGridProducto.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('eNuevoOriente');
eNuevoOriente.storeGridProducto = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        eNuevoOriente.storeGridProducto.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeGridProducto',
			idProperty: 'id_producto',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_producto'
                    
                },
				{
                    name: 'descripcion',
                    type: 'string'
                },
				{
                    name: 'codigo_barra',
                    type: 'string'
                },
				{
                    name: 'precio',
                    type: 'string'
                },
				{
                    name: 'status',
                    type: 'string'
                }
			
			],
            url: 'app.php/productos/obtenerproductos'
        }, cfg));
    }
});
Ext.reg('storeGridProducto', eNuevoOriente.storeGridProducto);