/*
 * File: formGastos.js
 * Date: Thu Feb 02 2017 23:47:25 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('eNuevoOriente');
formGastos = Ext.extend(formGastosUi, {
	idReg:0,
	idSeleccionado:0,
	configurarToobar:function(){
		
			this.btnAgregar.setIcon('images/iconos/servicios_add.png');
			this.btnEditar.setIcon('images/iconos/servicios_edit.png');
			this.btnEliminar.setIcon('images/iconos/servicios_delete.png');
			
		
		
	},
	inicializarStores: function(){
		
		this.gridGasto.store=new eNuevoOriente.storeGridGasto();
		this.gridGasto.bottomToolbar.bindStore(this.gridGasto.getStore());		
		this.cmbStatus.store = new eNuevoOriente.storeStatus();        				 
		this.gridGasto.bottomToolbar.pageSize=eNuevoOriente.parametros.registros_pagina;
		
		
		
	},
	inicializarEventos: function(){
		
		var dt = new Date();			
		this.txtFecha.setValue(dt);
		this.txtHora.setValue(dt.format('H:i:s A'));	
				 
		var data=new Array(
							{id:'A',nombre:eNuevoOriente.formatearTexto('ACTIVOS')},
							{id:'I',nombre:eNuevoOriente.formatearTexto('INACTIVOS')},
							{id:'T',nombre:eNuevoOriente.formatearTexto('TODOS')}
					);
			 this.cmbStatus.store.loadData({data:data});
			 this.cmbStatus.setValue(eNuevoOriente.formatearTexto('A'));	
		
		this.gridGasto.store.on('beforeload',function(){
				 
				this.gridGasto.store.baseParams=this.gridGasto.store.baseParams || {};
				this.gridGasto.store.baseParams.filtro=this.txtFiltro.getValue();
				this.gridGasto.store.baseParams.filtroStatus=this.cmbStatus.getValue();
			},this);
		
		this.gridGasto.store.on('load',function(){
			this.el.unmask();
		},this);
		
		
		this.btnGuardar.on('click', function(){
			this.guardar();		
		}, this);
		
		this.btnAgregar.on('click',function(){
			this.nuevo();
		},this);
		
		this.btnEditar.on('click',function(){
			var record = this.gridGasto.store.getAt(this.idSeleccionado);				
			this.idReg = record.data.id_gasto;
			this.txtFecha.setValue(eNuevoOriente.formatearTexto(record.data.fecha));
			this.txtHora.setValue(eNuevoOriente.formatearTexto(record.data.hora));
			this.txtConcepto.setValue(eNuevoOriente.formatearTexto(record.data.concepto));
			this.txtImporte.setValue(eNuevoOriente.formatearTexto(record.data.importe));
			this.txtStatus.setValue(record.data.status);
			this.txtConcepto.focus(true, 0);	
			this.btnDesactivar.setDisabled(false);
				
			
		},this);
		
		this.btnEliminar.on('click',function(){
			this.eliminar();
		},this);
		
		this.btnDesactivar.on('click',function(){	
			this.cancelar();			
		},this);
		
		this.txtFiltro.on('specialkey',function(comp,e){		
			if (e.getCharCode()==e.ENTER){
				this.gridGasto.bottomToolbar.doRefresh();
			}
		},this);
		
		this.cmbStatus.on('select',function(combo, record, index){	
				this.gridGasto.bottomToolbar.doRefresh();			
		},this);
		
		 this.gridGasto.on('rowclick', this.onRowClick, this);
		 
		 
		this.gridGasto.on('celldblclick', this.editar , this);

		this.on('cambioDeStatus',function(params){			
			var status=params.status;
			switch(status){
				case 'I':
					this.btnDesactivar.setIcon("images/iconos/servicios_green.png");
					this.btnDesactivar.setText("Activar");
				break;
				case 'A':
					this.btnDesactivar.setIcon("images/iconos/servicios_red.png");
					this.btnDesactivar.setText("Desactivar");
				break;
			}
		},this);		
		
	},
	initComponent: function() {
        formGastos.superclass.initComponent.call(this);
		this.gridGasto.columnaStatus="status";
		
		this.txtStatus.setValue=function(value){        	
        	Ext.form.TextField.prototype.setValue.apply(this,arguments);
        	this.fireEvent('cambioDeStatus',{status:value});
        };
		
		this.configurarToobar();
		this.inicializarStores();
		this.inicializarEventos();
		
    },
	guardar:function(){
		if (this.formGasto.getForm().isValid()){			
			var params={};
			
			var fecha = this.txtFecha.getValue();
			fecha=fecha.format('Y-m-d');  
						
			params['Gasto[id_gasto]'] = this.idReg;
			params['Gasto[fecha]'] = fecha;
			params['Gasto[hora]'] = this.txtHora.getValue();
			params['Gasto[concepto]'] = this.txtConcepto.getValue();
			params['Gasto[importe]'] = this.txtImporte.getValue();
					
			
			this.el.mask('Guardando...');
			this.formGasto.getForm().submit({
				params:params,
				scope:this,
				url:'app.php/gastos/guardar',
				success:function(){
					this.el.unmask();
					this.idReg=0;
					this.formGasto.getForm().reset();
					this.btnDesactivar.setDisabled(true);
					this.gridGasto.bottomToolbar.doRefresh();
				},
				failure:function(form, action){
					switch (action.failureType) {
		            case Ext.form.Action.CLIENT_INVALID:		                
		                msg="Favor de revisar los campos marcados";
		                icon=Ext.MessageBox.WARNING;
		                break;
		            case Ext.form.Action.CONNECT_FAILURE:		                
		                msg="Error en la comunicación ajax, intente de nuevo";
		                icon=Ext.MessageBox.ERROR;
		                break;
		            case Ext.form.Action.SERVER_INVALID:
		                icon=Ext.MessageBox.ERROR;
		                msg=action.result.msg;
					}
					Ext.Msg.show({
					   title:'Error',
					   msg: msg,
					   buttons: Ext.Msg.OK,						  						   
					   icon: icon
					});
					this.el.unmask();
					}

				});
				
			
		}else{
			return;
			
		}	
		
		
	},
	nuevo: function(){
		this.formGasto.getForm().reset();
		this.idReg = 0;
		this.txtConcepto.focus(true);
		this.btnDesactivar.setDisabled(true);
	},
	editar: function(Grid, rowIndex, columnIndex, e){		
		var record = this.gridGasto.store.getAt(rowIndex);				
		this.idReg = record.data.id_gasto;
		this.txtConcepto.setValue(eNuevoOriente.formatearTexto(record.data.concepto));
		this.txtFecha.setValue(eNuevoOriente.formatearTexto(record.data.fecha));
		this.txtHora.setValue(eNuevoOriente.formatearTexto(record.data.hora));
		this.txtImporte.setValue(eNuevoOriente.formatearTexto(record.data.importe));
		
		this.txtStatus.setValue(record.data.status);
		this.txtConcepto.focus(true, 0);	
		this.btnDesactivar.setDisabled(false);
		
		
	},
	eliminar:function(btn,id){
		switch(btn){	//ESTE SWITCH ES USADO PARA ANALIZAR LO QUE TRATA DE HACER EL USUARIO, LA PRIERA VEZ DEBE ENTRAR A default:
    	case 'no':
    		return;
    	break;
    	case 'yes':
    		this.eliminar('borrar');
    		return;
    		break;
    	case 'borrar':
    		break;		//SALE DEL SWITCH Y SIGUE EJECUTANDOSE LA FUNCI�N
    	case undefined:	//AQUI ENTRA LA PRIMERA VEZ
    	case false:    		
    	default:
    		var me=this;    		
    		Ext.Msg.show({
 			   title:'Confirme por favor',
 			   msg: "¿Desea eliminar el Gasto?",
 			   buttons: Ext.Msg.YESNO,
 			   fn: function(btn){	    				
    				me.eliminar(btn);
    			},
 			   scope:this,
 			   icon: Ext.MessageBox.QUESTION
 			});
    		return;
		} 
		
		if (id==undefined){	//obtener el id del registro seleccionado
    		var  sel=this.gridGasto.getSelectionModel().getSelections();
    		if (sel.length==undefined || sel.length==0){
    			return;
    		}else{
    			id=sel[0].id;    			
    		}
    	}
		
		this.el.mask(eno.mensajeDeEspera);
		Ext.Ajax.request({
			params: { id_gasto: id },
			scope:this,
		   	url: 'app.php/gastos/eliminar',
		   	success: function(response,options){	
				var respuesta=Ext.decode(response.responseText);
				if (respuesta.success==false){
					this.el.unmask();
					return;
				}
				this.idReg=0;
				this.formGasto.getForm().reset();
				this.btnDesactivar.setDisabled(true);
				this.gridGasto.bottomToolbar.doRefresh();			
				
		   	},
		   	failure: function(){
		   		this.el.unmask();
		   	}		   
		});
	},
	cancelar:function(){
		this.el.mask(eno.mensajeDeEspera);
		Ext.Ajax.request({
			params: { 
				id_gasto: this.idReg,
				status:this.txtStatus.getValue()
			},
			scope:this,
		   	url: 'app.php/gastos/cambiarstatus',
		   	success: function(response, options){
				this.el.unmask();			
				var respuesta=Ext.decode(response.responseText);
				if (respuesta.success==true){
						if (respuesta.data.status!=undefined){
							this.txtStatus.setValue(respuesta.data.status);
						}
					this.gridGasto.bottomToolbar.doRefresh();	
				}
		   	},
		   	failure: function(){
		   		this.el.unmask();
		   	}		   
		});
	},	
	onRowClick : function( grid ,rowIndex, e ){
		var  sel=this.gridGasto.getSelectionModel().getSelections();
		if (sel.length==undefined || sel.length==0){
			this.btnEditar.setDisabled(true);
		}else{
			this.btnEditar.setDisabled(false);
			this.idSeleccionado = rowIndex;
		}
		if (sel.length==undefined || sel.length==0){
			this.btnEliminar.setDisabled(true);
		}else{
			this.btnEliminar.setDisabled(false);
			this.idSeleccionado = rowIndex;
		}
		
	},
	listeners:{
		activate:function(){
			if (this.activado==true){
				return;
			}
			this.activado=true;
			this.gridGasto.bottomToolbar.doRefresh();
		}   	
    }
	
});
Ext.reg('formGastos', formGastos);
