/*
 * File: eNuevoOriente.storeGridGasto.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('eNuevoOriente');
eNuevoOriente.storeGridGasto = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        eNuevoOriente.storeGridGasto.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeGridGasto',
			idProperty: 'id_gasto',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_gasto'
                    
                },
				{
                    name: 'fecha',
                    type: 'string'
                },
				{
                    name: 'hora',
                    type: 'string'
                },
				{
                    name: 'concepto',
                    type: 'string'
                },
				{
                    name: 'importe',
                    type: 'string'
                },
				{
                    name: 'status',
                    type: 'string'
                }
			
			],
            url: 'app.php/gastos/obtenergastos'
        }, cfg));
    }
});
Ext.reg('storeGridGasto', eNuevoOriente.storeGridGasto);