/*
 * File: formAgentes.js
 * Date: Thu Feb 02 2017 23:47:25 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('eNuevoOriente');
formUsuarios = Ext.extend(formUsuariosUi, {
	idReg:0,
	idSeleccionado:0,
	configurarToobar:function(){
		
			this.btnAgregar.setIcon('images/iconos/user_add.png');
			this.btnEditar.setIcon('images/iconos/user_edit.png');
			this.btnEliminar.setIcon('images/iconos/user_delete.png');
			
		
		
	},
	renderRol:function(a,b,c,d){
		var rol='';
		switch(c.data.rol){
			case '1':
				rol='ADMINISTRADOR';
			break;
			case '2':
				rol='SUPERVISOR';
			break;
			case '3':
				rol='VENDEDOR';
			break;
		}
		
        rol=eNuevoOriente.formatearTexto(rol);
        


        // var RFCCliDet=c.data.RFCCliDet;
		// if (RFCCliDet==undefined){
			// RFCCliDet='';
		// }
        var div="<table>"+
        "<tr>"+
            "<td style='font-weight:bold;'>"+rol+"</td>"+
            "</tr>"+
        "</table>";
        return div;
	},
	renderContacto:function(a,b,c,d){

        var imgMail="<img style='width:12px;height:12px;' src='images/iconos/mail_chico.png' />";
        var msgMail;

		if(c.data.correo == null)
			msgMail= "";
		else
			msgMail= c.data.correo;	
        
		msgMail=msgMail.toLowerCase();
        if (c.data.correo==""){
            msgMail="<p style='font-style:italic'>sin email</p>";
        }            

      var div="<table>"+
            "<tr>"+
            "<td style='width:16px;'>"+imgMail+"</td>"+
            "<td>"+msgMail+"</td>"+
         "</tr>"+         
          "</table>";

      return div;
	},
	renderAuditoria:function(a,b,c,d){

        var img="<img class='btnAuditoria' style='width:12px;height:12px;' src='images/iconos/agent.png' />";
        var msg;

       
        msg= "Auditoría";
        
                  

      var div="<table>"+
            "<tr>"+
            "<td style='width:16px;'>"+img+"</td>"+
            "<td>"+msg+"</td>"+
         "</tr>"+         
          "</table>";

      return div;
	},
	inicializarStores: function(){
		
		this.gridUsuario.store=new eNuevoOriente.storeGridUsuario();
		this.gridUsuario.bottomToolbar.bindStore(this.gridUsuario.getStore());
		
		this.cmbStatus.store = new eNuevoOriente.storeStatus();        
		this.cmbRol.store = new eNuevoOriente.storeRol();	
		this.cmbAppLavadoras.store = new eNuevoOriente.storeSiNo();	
		this.cmbAppOrdenesServicio.store = new eNuevoOriente.storeSiNo();	
			 
		this.gridUsuario.bottomToolbar.pageSize=eNuevoOriente.parametros.registros_pagina;
		
		this.cmbTrabajador.store = new eNuevoOriente.storeTrabajadores();
		this.cmbTrabajador.store.load();	
	},
	inicializarEventos: function(){		
        var data=new Array(
							{id:'1',nombre:eNuevoOriente.formatearTexto('ADMINITRADOR')},
							{id:'2',nombre:eNuevoOriente.formatearTexto('SUPERVISOR')},
							{id:'3',nombre:eNuevoOriente.formatearTexto('VENDEDOR')}
					);		
		this.cmbRol.store.loadData({data:data}); 
		this.cmbRol.setValue(1);		
		
		var data=new Array(
							{id:'A',nombre:eNuevoOriente.formatearTexto('ACTIVOS')},
							{id:'I',nombre:eNuevoOriente.formatearTexto('INACTIVOS')},
							{id:'T',nombre:eNuevoOriente.formatearTexto('TODOS')}
					);
			 this.cmbStatus.store.loadData({data:data});
			 this.cmbStatus.setValue(eNuevoOriente.formatearTexto('A'));	
			 
		var data=new Array(
							{id:'0',nombre:eNuevoOriente.formatearTexto('NO')},
							{id:'1',nombre:eNuevoOriente.formatearTexto('SI')}
					);		
		this.cmbAppLavadoras.store.loadData({data:data}); 
		this.cmbAppLavadoras.setValue(0);

		this.cmbAppOrdenesServicio.store.loadData({data:data}); 
		this.cmbAppOrdenesServicio.setValue(0);	 	
		
		this.gridUsuario.store.on('beforeload',function(){
				 
				this.gridUsuario.store.baseParams=this.gridUsuario.store.baseParams || {};
				this.gridUsuario.store.baseParams.filtro=this.txtFiltro.getValue();
				this.gridUsuario.store.baseParams.filtroStatus=this.cmbStatus.getValue();
			},this);
		
		this.gridUsuario.store.on('load',function(){
			this.el.unmask();
		},this);
		
		
		this.btnGuardar.on('click', function(){
			this.guardar();		
		}, this);
		
		this.btnAgregar.on('click',function(){
			this.nuevo();
		},this);
		
		this.btnEditar.on('click',function(){
				var record = this.gridUsuario.store.getAt(this.idSeleccionado);				
				this.idReg = record.data.id_usuario;
				this.txtNombreUsuario.setValue(eNuevoOriente.formatearTexto(record.data.nombre_usuario));
				this.txtUsuario.setValue(eNuevoOriente.formatearSinFormato(record.data.usuario));
				this.txtPass.setValue(eNuevoOriente.formatearSinFormato(record.data.pass));
				this.txtCorreo.setValue(eNuevoOriente.formatearCorreo(record.data.correo));
				this.cmbRol.setValue(record.data.rol);
				this.cmbAppLavadoras.setValue(record.data.app_lavadoras);
				this.cmbAppOrdenesServicio.setValue(record.data.app_ordenes_servicio);
				this.cmbTrabajador.setValue(record.data.id_trabajador);
				this.txtStatus.setValue(record.data.status);
				this.txtNombreUsuario.focus(true, 0);
				this.btnDesactivar.setDisabled(false);	
				
			
		},this);
		
		this.btnEliminar.on('click',function(){
			this.eliminar();
		},this);
		
		this.btnDesactivar.on('click',function(){	
			this.cancelar();			
		},this);
		
		this.txtFiltro.on('specialkey',function(comp,e){		
			if (e.getCharCode()==e.ENTER){
				this.gridUsuario.bottomToolbar.doRefresh();
			}
		},this);
		
		this.cmbStatus.on('select',function(combo, record, index){	
				this.gridUsuario.bottomToolbar.doRefresh();			
		},this);
		
		 this.gridUsuario.on('rowclick', this.onRowClick, this);
		 
		 
		this.gridUsuario.on('celldblclick', this.editar , this);

		this.on('cambioDeStatus',function(params){			
			var status=params.status;
			switch(status){
				case 'I':
					this.btnDesactivar.setIcon("images/iconos/user_activos.png");
					this.btnDesactivar.setText("Activar");
				break;
				case 'A':
					this.btnDesactivar.setIcon("images/iconos/user_todos.png");
					this.btnDesactivar.setText("Desactivar");
				break;
			}
		},this);		
		
		this.cmbTrabajador.addListener('beforequery',function(qe){
			delete qe.combo.lastQuery; 	//PARA QUE SIEMPRE REALICE LA CONSULTA AL SERVIDOR
		},this);
		
		this.gridUsuario.getColumnModel().getColumnById("colAuditoria").renderer=function(v,m,rec){value="<img class='btnAuditoria' src='images/iconos/agent.png' style='cursor:pointer;' />";return value;}
		
		//abrir la ventana de auditoria cuando se le da click a la imagen en el grid, mardar el id del modulo y el id
		this.gridUsuario.on("cellclick",function(Grid,rowIndex,columnIndex,e){
			var imgEl=Ext.get(e.getTarget());
			if(imgEl.hasClass("btnAuditoria")){
				console.log('btnAuditoria');
				var record=this.gridUsuario.getStore().getAt(rowIndex);
				console.log(record);
				
			}
		},this);
		
		
		
	},
	inicializarRender: function(){
		var colModel=this.gridUsuario.getColumnModel();
        var columna=colModel.getColumnById('colRol');
        columna.renderer=this.renderRol;

		var colModel=this.gridUsuario.getColumnModel();
        var columna=colModel.getColumnById('colCorreo');
        columna.renderer=this.renderContacto;
		
		/*var colModel=this.gridUsuario.getColumnModel();
        var columna=colModel.getColumnById('colAuditoria');
        columna.renderer=this.renderAuditoria;*/
		
		
	},
    initComponent: function() {
        formUsuarios.superclass.initComponent.call(this);
		this.gridUsuario.columnaStatus="status";
		
		this.txtStatus.setValue=function(value){        	
        	Ext.form.TextField.prototype.setValue.apply(this,arguments);
        	this.fireEvent('cambioDeStatus',{status:value});
        };
		
		this.configurarToobar();
		this.inicializarStores();
		this.inicializarEventos();
		this.inicializarRender();
    },
	guardar:function(){
		if (this.formUsuario.getForm().isValid()){			
			var params={};			
			params['Usuario[id_usuario]'] = this.idReg;
			params['Usuario[nombre_usuario]'] = this.txtNombreUsuario.getValue();
			params['Usuario[usuario]'] = this.txtUsuario.getValue();
			params['Usuario[pass]'] = this.txtPass.getValue();
			params['Usuario[correo]'] = this.txtCorreo.getValue();
			params['Usuario[rol]'] = this.cmbRol.getValue();
			params['Usuario[app_lavadoras]'] = this.cmbAppLavadoras.getValue();
			params['Usuario[app_ordenes_servicio]'] = this.cmbAppOrdenesServicio.getValue();
			params['Usuario[id_trabajador]'] = this.cmbTrabajador.getValue();				
			
			this.el.mask('Guardando...');
			this.formUsuario.getForm().submit({
				params:params,
				scope:this,
				url:'app.php/usuarios/guardar',
				success:function(){
					this.el.unmask();
					this.idReg=0;
					this.formUsuario.getForm().reset();
					this.btnDesactivar.setDisabled(true);
					this.gridUsuario.bottomToolbar.doRefresh();
				},
				failure:function(form, action){
					switch (action.failureType) {
		            case Ext.form.Action.CLIENT_INVALID:		                
		                msg="Favor de revisar los campos marcados";
		                icon=Ext.MessageBox.WARNING;
		                break;
		            case Ext.form.Action.CONNECT_FAILURE:		                
		                msg="Error en la comunicación ajax, intente de nuevo";
		                icon=Ext.MessageBox.ERROR;
		                break;
		            case Ext.form.Action.SERVER_INVALID:
		                icon=Ext.MessageBox.ERROR;
		                msg=action.result.msg;
					}
					Ext.Msg.show({
					   title:'Error',
					   msg: msg,
					   buttons: Ext.Msg.OK,						  						   
					   icon: icon
					});
					this.el.unmask();
					}

				});
				
			
		}else{
			return;
			
		}	
		
		
	},
	nuevo: function(){
		this.formUsuario.getForm().reset();
		this.idReg = 0;
		this.txtNombreUsuario.focus(true);
		this.btnDesactivar.setDisabled(true);
	},
	editar: function(Grid, rowIndex, columnIndex, e){		
		var record = this.gridUsuario.store.getAt(rowIndex);				
		this.idReg = record.data.id_usuario;
		this.txtNombreUsuario.setValue(eNuevoOriente.formatearTexto(record.data.nombre_usuario));
		this.txtUsuario.setValue(eNuevoOriente.formatearSinFormato(record.data.usuario));
		this.txtPass.setValue(eNuevoOriente.formatearSinFormato(record.data.pass));
		this.txtCorreo.setValue(eNuevoOriente.formatearCorreo(record.data.correo));
		this.cmbRol.setValue(record.data.rol);
		this.cmbAppLavadoras.setValue(record.data.app_lavadoras);
		this.cmbAppOrdenesServicio.setValue(record.data.app_ordenes_servicio);
		this.cmbTrabajador.setValue(record.data.id_trabajador);
		this.txtStatus.setValue(record.data.status);
		this.txtNombreUsuario.focus(true, 0);	
		this.btnDesactivar.setDisabled(false);
		
		
	},
	eliminar:function(btn,id){
		switch(btn){	//ESTE SWITCH ES USADO PARA ANALIZAR LO QUE TRATA DE HACER EL USUARIO, LA PRIERA VEZ DEBE ENTRAR A default:
    	case 'no':
    		return;
    	break;
    	case 'yes':
    		this.eliminar('borrar');
    		return;
    		break;
    	case 'borrar':
    		break;		//SALE DEL SWITCH Y SIGUE EJECUTANDOSE LA FUNCI�N
    	case undefined:	//AQUI ENTRA LA PRIMERA VEZ
    	case false:    		
    	default:
    		var me=this;    		
    		Ext.Msg.show({
 			   title:'Confirme por favor',
 			   msg: "¿Desea eliminar el Usuario?",
 			   buttons: Ext.Msg.YESNO,
 			   fn: function(btn){	    				
    				me.eliminar(btn);
    			},
 			   scope:this,
 			   icon: Ext.MessageBox.QUESTION
 			});
    		return;
		} 
		
		if (id==undefined){	//obtener el id del registro seleccionado
    		var  sel=this.gridUsuario.getSelectionModel().getSelections();
    		if (sel.length==undefined || sel.length==0){
    			return;
    		}else{
    			id=sel[0].id;    			
    		}
    	}
		
		this.el.mask(eno.mensajeDeEspera);
		Ext.Ajax.request({
			params: { id_usuario: id },
			scope:this,
		   	url: 'app.php/usuarios/eliminar',
		   	success: function(response,options){	
				var respuesta=Ext.decode(response.responseText);
				if (respuesta.success==false){
					this.el.unmask();
					return;
				}
				this.idReg=0;
				this.formUsuario.getForm().reset();
				this.btnDesactivar.setDisabled(true);
				this.gridUsuario.bottomToolbar.doRefresh();			
				
		   	},
		   	failure: function(){
		   		this.el.unmask();
		   	}		   
		});
	},
	cancelar:function(){
		this.el.mask(eno.mensajeDeEspera);
		Ext.Ajax.request({
			params: { 
				id_usuario: this.idReg,
				status:this.txtStatus.getValue()
			},
			scope:this,
		   	url: 'app.php/usuarios/cambiarstatus',
		   	success: function(response, options){
				this.el.unmask();			
				var respuesta=Ext.decode(response.responseText);
				if (respuesta.success==true){
						if (respuesta.data.status!=undefined){
							this.txtStatus.setValue(respuesta.data.status);
						}
					this.gridUsuario.bottomToolbar.doRefresh();	
				}
		   	},
		   	failure: function(){
		   		this.el.unmask();
		   	}		   
		});
	},	
	onRowClick : function( grid ,rowIndex, e ){
		var  sel=this.gridUsuario.getSelectionModel().getSelections();
		if (sel.length==undefined || sel.length==0){
			this.btnEditar.setDisabled(true);
		}else{
			this.btnEditar.setDisabled(false);
			this.idSeleccionado = rowIndex;
		}
		if (sel.length==undefined || sel.length==0){
			this.btnEliminar.setDisabled(true);
		}else{
			this.btnEliminar.setDisabled(false);
			this.idSeleccionado = rowIndex;
		}
		
	},
	listeners:{
		activate:function(){
			if (this.activado==true){
				return;
			}
			this.activado=true;
			this.gridUsuario.bottomToolbar.doRefresh();
		}   	
    }
	
});
Ext.reg('formUsuarios', formUsuarios);
