/*
 * File: mfw.almacenes.storeTrabajadores.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('eNuevoOriente');
eNuevoOriente.storeTrabajadores = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        eNuevoOriente.storeTrabajadores.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeTrabajadores',
			autoDestroy: true,
			idProperty: 'id_trabajador',
			messageProperty: 'msg',
			url: 'app.php/usuarios/obtenertrabajadores',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[{
						name: 'id_trabajador',
						type: 'int'
					},{
						name: 'nombre_trabajador',
						type: 'string'
					},
					{
						name: 'id_ruta',
						type: 'int'
					},
					{
						name: 'ruta',
						type: 'string'
					}
			]
        }, cfg));
    }
});
Ext.reg('storeTrabajadores', eNuevoOriente.storeTrabajadores);
