/*
 * File: miErpWeb.storeGridUsuario.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('eNuevoOriente');
eNuevoOriente.storeGridUsuario = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        eNuevoOriente.storeGridUsuario.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeGridUsuario',
			idProperty: 'id_usuario',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_usuario'
                    
                },
				{
                    name: 'id_trabajador'
                    
                },
				{
                    name: 'nombre_usuario',
                    type: 'string'
                },
				{
                    name: 'usuario',
                    type: 'string'
                },
				{
                    name: 'pass',
                    type: 'string'
                },
				{
                    name: 'correo',
                    type: 'string'
                },
				{
                    name: 'rol',
                    type: 'string'
                },
				{
                    name: 'app_lavadoras',
                    type: 'string'
                },
				{
                    name: 'app_ordenes_servicio',
                    type: 'string'
                },
				{
                    name: 'status',
                    type: 'string'
                }
			
			],
            url: 'app.php/usuarios/obtenerusuarios'
        }, cfg));
    }
});
Ext.reg('storeGridUsuario', eNuevoOriente.storeGridUsuario);