/*
 * File: main.ui.js
 * Date: Sun Mar 13 2016 18:17:12 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

mainUi = Ext.extend(Ext.Panel, {
    width: 528,
    height: 251,
    cls: 'LoginMain',
    style: 'position:absolute;font-family:arial',
    unstyled: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                width: 430,
                height: 251,
                layout: 'card',
                activeItem: 1,
                hideBorders: true,
                border: false,
                style: 'position:absolute;left:50%;margin-left:-180px;top:95px;',
                bodyStyle: 'background:none;',
                ref: 'cardLogin',
                id: 'cardLogin',
                items: [
                    {
                        xtype: 'form',
                        width: 360,
                        height: 160,
                        labelWidth: 110,
                        hideBorders: true,
                        border: false,
                        unstyled: true,
                        bubbleEvents: '',
                        ref: '../frmLogin',
                        id: 'frmLogin',
                        items: [
                            {
                                xtype: 'panel',
                                layout: 'hbox',
                                unstyled: true,
                                style: 'margin-bottom:15px;',
                                items: [
                                    {
                                        xtype: 'displayfield',
                                        value: 'Correo Electrónico:',
                                        style: 'font-size: 13px;',
                                        width: 150
                                    },
                                    {
                                        xtype: 'textfield',
                                        flex: 1,
                                        width: 214,
                                        allowBlank: false,
                                        name: 'username',
                                        style: 'margin-bottom:10px;',
                                        enableKeyEvents: true,
                                        selectOnFocus: true,
                                        itemId: 'txtUsername',
                                        tabIndex: 1,
                                        bubbleEvents: [
                                            'keyup'
                                        ],
                                        ref: '../../../txtUsername'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                layout: 'hbox',
                                unstyled: true,
                                hideBorders: true,
                                border: false,
                                style: 'margin-bottom:10px;',
                                items: [
                                    {
                                        xtype: 'displayfield',
                                        value: 'Contraseña:',
                                        flex: 1,
                                        style: 'font-size: 13px;',
                                        width: 150
                                    },
                                    {
                                        xtype: 'textfield',
                                        flex: 1,
                                        width: 214,
                                        allowBlank: false,
                                        name: 'pass',
                                        inputType: 'password',
                                        enableKeyEvents: true,
                                        selectOnFocus: true,
                                        itemId: 'txtPass',
                                        tabIndex: 2,
                                        bubbleEvents: [
                                            'enterPassword',
                                            'keyup'
                                        ],
                                        ref: '../../../txtPass'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                layout: 'absolute',
                                height: 30,
                                width: 360,
                                unstyled: true,
                                style: 'margin-top:5px;',
                                items: [
                                    {
                                        xtype: 'button',
                                        text: 'Entrar',
                                        width: 100,
                                        style: 'left:50%;margin-left:-105px;',
                                        tabIndex: 3,
                                        bubbleEvents: [
                                            "click"
                                        ],
                                        itemId: 'btnIdentificar',
                                        height: 25,
                                        ref: '../../../btnIdentificar'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Salir',
                                        width: 100,
                                        style: 'left:50%;margin-left:20px;',
                                        itemId: 'salir',
                                        tabIndex: 4,
                                        bubbleEvents: [
                                            "click"
                                        ],
                                        height: 25,
                                        ref: '../../../btnSalir'
                                    }
                                ]
                            }
                        ]
                    },
                    
                ]
            }
        ];
        mainUi.superclass.initComponent.call(this);
    }
});
