/*
 * File: mfw.almacenes.storeRuta.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('eNuevoOriente');
eNuevoOriente.storeRuta = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        eNuevoOriente.storeRuta.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeRuta',
			autoDestroy: true,
			idProperty: 'id_ruta',
			messageProperty: 'msg',
			url: 'app.php/clientes/obtenerrutas',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[{
						name: 'id_ruta',
						type: 'int'
					},{
						name: 'descripcion',
						type: 'string'
					}
			]
        }, cfg));
    }
});
Ext.reg('storeRuta', eNuevoOriente.storeRuta);
