/*
 * File: formTrabajadores.js
 * Date: Thu Feb 02 2017 23:47:25 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('eNuevoOriente');
formTrabajadores = Ext.extend(formTrabajadoresUi, {
	idReg:0,
	idSeleccionado:0,
	configurarToobar:function(){
		
			this.btnAgregar.setIcon('images/iconos/clientes_add.png');
			this.btnEditar.setIcon('images/iconos/clientes_edit.png');
			this.btnEliminar.setIcon('images/iconos/clientes_delete.png');
			
		
		
	},
	renderTelefono1:function(a,b,c,d){
        var imgTel="<img src='images/iconos/users_grid/telephone.png' />";

        var msgTel;

        msgTel=c.data.telefono1;
        
                
        if (c.data.telefono1==""){
          //  imgTel="";
            msgTel="<p style='font-style:italic'>sin teléfono</p>";
        }
       
		var div="<table>"+
          "<tr>"+
            "<td style='width:16px;'>"+imgTel+"</td>"+
            "<td>"+msgTel+"</td>"+
         "</tr>"+
         "</table>";

		return div;
    },
	renderTelefono2:function(a,b,c,d){
        var imgTel="<img src='images/iconos/users_grid/telephone.png' />";

        var msgTel;

        msgTel=c.data.telefono2;
        
                
        if (c.data.telefono2==""){
          //  imgTel="";
            msgTel="<p style='font-style:italic'>sin teléfono</p>";
        }
       
		var div="<table>"+
          "<tr>"+
            "<td style='width:16px;'>"+imgTel+"</td>"+
            "<td>"+msgTel+"</td>"+
         "</tr>"+
         "</table>";

		return div;
    },
	renderCelular:function(a,b,c,d){
        var imgCel="<img src='images/iconos/users_grid/smartphone.png' />";
       

        var msgCel;

        msgCel=c.data.celular;
        
        if (c.data.celular==""){
          //  imgCel="";
            msgCel="<p style='font-style:italic'>sin celular</p>";
        }

      var div="<table>"+
          "<tr>"+
            "<td style='width:16px;'>"+imgCel+"</td>"+
            "<td>"+msgCel+"</td>"+
         "</tr>"+
          "</table>";

      return div;
    },
	renderTipo:function(a,b,c,d){
		var tipo='';
		switch(c.data.tipo){
			case '1':
				tipo='CHOFER';
			break;
			case '2':
				tipo='COBRADOR';
			break;
			case '3':
				tipo='TECNICO';
			break;
		}
		
        tipo=eNuevoOriente.formatearTexto(tipo);
        


        // var RFCCliDet=c.data.RFCCliDet;
		// if (RFCCliDet==undefined){
			// RFCCliDet='';
		// }
        var div="<table>"+
        "<tr>"+
            "<td style='font-weight:bold;'>"+tipo+"</td>"+
            "</tr>"+
        "</table>";
        return div;
	},
	inicializarStores: function(){
		
		this.gridTrabajador.store=new eNuevoOriente.storeGridTrabajador();
		this.gridTrabajador.bottomToolbar.bindStore(this.gridTrabajador.getStore());
		this.cmbTipo.store = new eNuevoOriente.storeTipo();
		this.cmbStatus.store = new eNuevoOriente.storeStatus();        
		this.cmbRuta.store = new eNuevoOriente.storeRuta();	
		this.cmbRuta.store.load();		 
		this.gridTrabajador.bottomToolbar.pageSize=eNuevoOriente.parametros.registros_pagina;
		
		
		
	},
	inicializarEventos: function(){
		var data=new Array(
							{id:'1',nombre:eNuevoOriente.formatearTexto('CHOFER')},
							{id:'2',nombre:eNuevoOriente.formatearTexto('COBRADOR')},
							{id:'3',nombre:eNuevoOriente.formatearTexto('TECNICO')}
					);		
		this.cmbTipo.store.loadData({data:data}); 
		this.cmbTipo.setValue(1);	
		 
		var data=new Array(
							{id:'A',nombre:eNuevoOriente.formatearTexto('ACTIVOS')},
							{id:'I',nombre:eNuevoOriente.formatearTexto('INACTIVOS')},
							{id:'T',nombre:eNuevoOriente.formatearTexto('TODOS')}
					);
			 this.cmbStatus.store.loadData({data:data});
			 this.cmbStatus.setValue(eNuevoOriente.formatearTexto('A'));	
		
		this.gridTrabajador.store.on('beforeload',function(){
				 
				this.gridTrabajador.store.baseParams=this.gridTrabajador.store.baseParams || {};
				this.gridTrabajador.store.baseParams.filtro=this.txtFiltro.getValue();
				this.gridTrabajador.store.baseParams.filtroStatus=this.cmbStatus.getValue();
			},this);
		
		this.gridTrabajador.store.on('load',function(){
			this.el.unmask();
		},this);
		
		
		this.btnGuardar.on('click', function(){
			this.guardar();		
		}, this);
		
		this.btnAgregar.on('click',function(){
			this.nuevo();
		},this);
		
		this.btnEditar.on('click',function(){
			var record = this.gridTrabajador.store.getAt(this.idSeleccionado);				
			this.idReg = record.data.id_trabajador;
			this.txtNombre.setValue(eNuevoOriente.formatearTexto(record.data.nombre));
			this.txtDireccion.setValue(eNuevoOriente.formatearTexto(record.data.direccion));
			this.txtCURP.setValue(eNuevoOriente.formatearTexto(record.data.curp));
			this.txtNumCredencial.setValue(eNuevoOriente.formatearTexto(record.data.num_credencial));
			this.txtTelefono1.setValue(eNuevoOriente.formatearTexto(record.data.telefono1));
			this.txtTelefono2.setValue(eNuevoOriente.formatearTexto(record.data.telefono2));
			this.txtCelular.setValue(eNuevoOriente.formatearTexto(record.data.celular));
			this.cmbTipo.setValue(record.data.tipo);			
			this.cmbRuta.setValue(record.data.id_ruta);			
			this.txtStatus.setValue(record.data.status);
			this.txtNombre.focus(true, 0);	
			this.btnDesactivar.setDisabled(false);
				
			
		},this);
		
		this.btnEliminar.on('click',function(){
			this.eliminar();
		},this);
		
		this.btnDesactivar.on('click',function(){	
			this.cancelar();			
		},this);
		
		this.txtFiltro.on('specialkey',function(comp,e){		
			if (e.getCharCode()==e.ENTER){
				this.gridTrabajador.bottomToolbar.doRefresh();
			}
		},this);
		
		this.cmbStatus.on('select',function(combo, record, index){	
				this.gridTrabajador.bottomToolbar.doRefresh();			
		},this);
		
		 this.gridTrabajador.on('rowclick', this.onRowClick, this);
		 
		 
		this.gridTrabajador.on('celldblclick', this.editar , this);

		this.on('cambioDeStatus',function(params){			
			var status=params.status;
			switch(status){
				case 'I':
					this.btnDesactivar.setIcon("images/iconos/clientes_activos.png");
					this.btnDesactivar.setText("Activar");
				break;
				case 'A':
					this.btnDesactivar.setIcon("images/iconos/clientes_todos.png");
					this.btnDesactivar.setText("Desactivar");
				break;
			}
		},this);		
		
	},
	inicializarRender: function(){
		var colModel=this.gridTrabajador.getColumnModel();
        var columna=colModel.getColumnById('colTelefono1');
        columna.renderer=this.renderTelefono1	
		
		var colModel=this.gridTrabajador.getColumnModel();
        var columna=colModel.getColumnById('colTelefono2');
        columna.renderer=this.renderTelefono2
		
		var colModel=this.gridTrabajador.getColumnModel();
        var columna=colModel.getColumnById('colCelular');
        columna.renderer=this.renderCelular
		
		var colModel=this.gridTrabajador.getColumnModel();
        var columna=colModel.getColumnById('colTipo');
        columna.renderer=this.renderTipo

		
	},
    initComponent: function() {
        formTrabajadores.superclass.initComponent.call(this);
		this.gridTrabajador.columnaStatus="status";
		
		this.txtStatus.setValue=function(value){        	
        	Ext.form.TextField.prototype.setValue.apply(this,arguments);
        	this.fireEvent('cambioDeStatus',{status:value});
        };
		
		this.configurarToobar();
		this.inicializarStores();
		this.inicializarEventos();
		this.inicializarRender();
    },
	guardar:function(){
		if (this.formTrabajador.getForm().isValid()){			
			var params={};			
			params['Trabajador[id_trabajador]'] = this.idReg;
			params['Trabajador[nombre]'] = this.txtNombre.getValue();
			params['Trabajador[direccion]'] = this.txtDireccion.getValue();
			params['Trabajador[curp]'] = this.txtCURP.getValue();
			params['Trabajador[num_credencial]'] = this.txtNumCredencial.getValue();
			params['Trabajador[telefono1]'] = this.txtTelefono1.getValue();
			params['Trabajador[telefono2]'] = this.txtTelefono2.getValue();
			params['Trabajador[celular]'] = this.txtCelular.getValue();
			params['Trabajador[tipo]'] = this.cmbTipo.getValue();
			params['Trabajador[id_ruta]'] = this.cmbRuta.getValue();			
			
			this.el.mask('Guardando...');
			this.formTrabajador.getForm().submit({
				params:params,
				scope:this,
				url:'app.php/trabajadores/guardar',
				success:function(){
					this.el.unmask();
					this.idReg=0;
					this.formTrabajador.getForm().reset();
					this.btnDesactivar.setDisabled(true);
					this.gridTrabajador.bottomToolbar.doRefresh();
				},
				failure:function(form, action){
					switch (action.failureType) {
		            case Ext.form.Action.CLIENT_INVALID:		                
		                msg="Favor de revisar los campos marcados";
		                icon=Ext.MessageBox.WARNING;
		                break;
		            case Ext.form.Action.CONNECT_FAILURE:		                
		                msg="Error en la comunicación ajax, intente de nuevo";
		                icon=Ext.MessageBox.ERROR;
		                break;
		            case Ext.form.Action.SERVER_INVALID:
		                icon=Ext.MessageBox.ERROR;
		                msg=action.result.msg;
					}
					Ext.Msg.show({
					   title:'Error',
					   msg: msg,
					   buttons: Ext.Msg.OK,						  						   
					   icon: icon
					});
					this.el.unmask();
					}

				});
				
			
		}else{
			return;
			
		}	
		
		
	},
	nuevo: function(){
		this.formTrabajador.getForm().reset();
		this.idReg = 0;
		this.txtNombre.focus(true);
		this.btnDesactivar.setDisabled(true);
	},
	editar: function(Grid, rowIndex, columnIndex, e){		
		var record = this.gridTrabajador.store.getAt(rowIndex);				
		this.idReg = record.data.id_trabajador;
		this.txtNombre.setValue(eNuevoOriente.formatearTexto(record.data.nombre));
		this.txtDireccion.setValue(eNuevoOriente.formatearTexto(record.data.direccion));
		this.txtCURP.setValue(eNuevoOriente.formatearTexto(record.data.curp));
		this.txtNumCredencial.setValue(eNuevoOriente.formatearTexto(record.data.num_credencial));
		this.txtTelefono1.setValue(eNuevoOriente.formatearTexto(record.data.telefono1));
		this.txtTelefono2.setValue(eNuevoOriente.formatearTexto(record.data.telefono2));
		this.txtCelular.setValue(eNuevoOriente.formatearTexto(record.data.celular));
		this.cmbTipo.setValue(record.data.tipo);		
		this.cmbRuta.setValue(record.data.id_ruta);
		this.txtStatus.setValue(record.data.status);
		this.txtNombre.focus(true, 0);	
		this.btnDesactivar.setDisabled(false);
		
		
	},
	eliminar:function(btn,id){
		switch(btn){	//ESTE SWITCH ES USADO PARA ANALIZAR LO QUE TRATA DE HACER EL USUARIO, LA PRIERA VEZ DEBE ENTRAR A default:
    	case 'no':
    		return;
    	break;
    	case 'yes':
    		this.eliminar('borrar');
    		return;
    		break;
    	case 'borrar':
    		break;		//SALE DEL SWITCH Y SIGUE EJECUTANDOSE LA FUNCI�N
    	case undefined:	//AQUI ENTRA LA PRIMERA VEZ
    	case false:    		
    	default:
    		var me=this;    		
    		Ext.Msg.show({
 			   title:'Confirme por favor',
 			   msg: "¿Desea eliminar el Trabajador?",
 			   buttons: Ext.Msg.YESNO,
 			   fn: function(btn){	    				
    				me.eliminar(btn);
    			},
 			   scope:this,
 			   icon: Ext.MessageBox.QUESTION
 			});
    		return;
		} 
		
		if (id==undefined){	//obtener el id del registro seleccionado
    		var  sel=this.gridTrabajador.getSelectionModel().getSelections();
    		if (sel.length==undefined || sel.length==0){
    			return;
    		}else{
    			id=sel[0].id;    			
    		}
    	}
		
		this.el.mask(eno.mensajeDeEspera);
		Ext.Ajax.request({
			params: { id_trabajador: id },
			scope:this,
		   	url: 'app.php/trabajadores/eliminar',
		   	success: function(response,options){	
				var respuesta=Ext.decode(response.responseText);
				if (respuesta.success==false){
					this.el.unmask();
					return;
				}
				this.idReg=0;
				this.formTrabajador.getForm().reset();
				this.btnDesactivar.setDisabled(true);
				this.gridTrabajador.bottomToolbar.doRefresh();			
				
		   	},
		   	failure: function(){
		   		this.el.unmask();
		   	}		   
		});
	},
	cancelar:function(){
		this.el.mask(eno.mensajeDeEspera);
		Ext.Ajax.request({
			params: { 
				id_trabajador: this.idReg,
				status:this.txtStatus.getValue()
			},
			scope:this,
		   	url: 'app.php/trabajadores/cambiarstatus',
		   	success: function(response, options){
				this.el.unmask();			
				var respuesta=Ext.decode(response.responseText);
				if (respuesta.success==true){
						if (respuesta.data.status!=undefined){
							this.txtStatus.setValue(respuesta.data.status);
						}
					this.gridTrabajador.bottomToolbar.doRefresh();	
				}
		   	},
		   	failure: function(){
		   		this.el.unmask();
		   	}		   
		});
	},	
	onRowClick : function( grid ,rowIndex, e ){
		var  sel=this.gridTrabajador.getSelectionModel().getSelections();
		if (sel.length==undefined || sel.length==0){
			this.btnEditar.setDisabled(true);
		}else{
			this.btnEditar.setDisabled(false);
			this.idSeleccionado = rowIndex;
		}
		if (sel.length==undefined || sel.length==0){
			this.btnEliminar.setDisabled(true);
		}else{
			this.btnEliminar.setDisabled(false);
			this.idSeleccionado = rowIndex;
		}
		
	},
	listeners:{
		activate:function(){
			if (this.activado==true){
				return;
			}
			this.activado=true;
			this.gridTrabajador.bottomToolbar.doRefresh();
		}   	
    }
	
});
Ext.reg('formTrabajadores', formTrabajadores);
