/*
 * File: formReporteInventario.js
 * Date: Thu Feb 02 2017 23:47:25 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
Ext.ns('eNuevoOriente');
formReporteInventario = Ext.extend(formReporteInventarioUi, {
	idReg:0,
	idSeleccionado:0,
	inicializarStores: function(){
					
		
		this.cmbProducto.store =  new eNuevoOriente.storeFormReporteInventarioProductos();
		this.cmbProducto.store.load();	
		
	  
	},
	inicializarEventos: function(){
		var me = this;
		
		this.cmbProducto.addListener('beforequery',function(qe){
			delete qe.combo.lastQuery; 	//PARA QUE SIEMPRE REALICE LA CONSULTA AL SERVIDOR
		},this);
		
		this.cmbProducto.onTriggerClick = function(a, e){
			if(e){
				if(e.getAttribute('class').indexOf('x-form-clear-trigger') > -1){
					if(this.isExpanded()){
						this.collapse();
						this.el.focus();
					}
					if(!Ext.isEmpty(me.cmbProducto.getValue())){
						this.reset();	
						
						
					}
				}else{
					if(this.readOnly || this.disabled){
						return;
					}
					if(this.isExpanded()){
						this.collapse();
						this.el.focus();
					}else {
						this.onFocus({});
						if(this.triggerAction == 'all') {
							this.doQuery(this.allQuery, true);
						} else {
							this.doQuery(this.getRawValue());
						}
						this.el.focus();
					}
				} 
			}
		};
		
				
		
		this.btnPDF.on('click', function(){
			this.imprimirPDF();
		}, this);	
				
		this.btnExcel.on('click', function(){
			this.imprimirExcel();
		}, this);	
						
		
	},
	inizializaTpls:function(){
		this.cmbProducto.tpl = new Ext.XTemplate(
			'<tpl for=".">'+
				'<div class="x-combo-list-item">'+
					'<div><b>{descripcion}</b></div>'+
					'<div><i>{codigo_barra}</i></div>'+
					
				'</div>'+
			'</tpl>'
		);
		
		
		
	},
	getParamsImprimir:function(){
		return {
			id_producto:this.cmbProducto.getValue() || 0
		};
		
		
				
	},
	imprimirPDF:function(){
		if (!this.getForm().isValid()) {	//<---Si hay errores informa al usuario
			 return false;
		}
		var params=this.getParamsImprimir();			
		Ext.Ajax.request({
		params: params,
		   url: 'app.php/productos/generarreporteinventario',
		   success: function(response, opts){
				//Solicita el PDF
				var obj = Ext.decode(response.responseText);
				if (!obj.success){	//Prosegir solo en caso de exito
					return;
				}
				var identificador=obj.data.identificador;
				window.open("app.php/productos/getpdfinventarios?identificador="+identificador,'rep_mov',"height=600,width=800");							
			},
		   failure: function(){
				alert("El servidor ha respondido con un mensaje de error");
			}						   
		   
		});
	},
	
	imprimirExcel: function(){
		if (!this.getForm().isValid()) {	//<---Si hay errores informa al usuario
			 return false;
		}
		var params=this.getParamsImprimir();			
		
		location.href = "app.php/productos/generarreporteinventariosexcel?id_producto="+params.id_producto;
	},
	
	initComponent: function() {
        formReporteInventario.superclass.initComponent.call(this);
		
		this.inicializarStores();
		this.inicializarEventos();
		this.inizializaTpls();
		
		
    }
	
});
Ext.reg('formReporteInventario', formReporteInventario);
