/*
 * File: formRentasDiasExtraWindow.ui.js
 * Date: Tue Dec 25 2018 23:34:27 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

formRentasDiasExtraWindowUi = Ext.extend(Ext.Window, {
    title: 'Dias Extra',
    width: 300,
    height: 100,
    modal: true,
    border: false,
    draggable: false,
    resizable: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
				itemId: 'formRentasDiasExtraWindow',
				border: false,
				ref: 'formRentasDiasExtraWindow',
				padding: 10,
				items: [
					{
						xtype: 'container',
						layout: 'hbox',
						items:[
							{
								xtype: 'container',
								layout: 'form',
								flex: 1,
								//width:100,
								items:[
									{
										xtype: 'numberfield',
										fieldLabel: 'Dias extra',
										itemId: 'txtDiasExtra',
										name: 'dias_extra',
										width: 100,
										allowNegative: false,
										submitValue: false,
										allowBlank: false,
										style: 'text-align: right',
										ref: '../../../txtDiasExtra'
									}
								]
							}
						]
					},
				],
				bbar: {
								xtype: 'toolbar',
								buttonAlign: 'right',
								items: [
									{
										xtype: 'button',
										text: 'Guardar',
										icon: 'images/iconos/save.png',
										itemId: 'btnGuardar',
										ref: '../../btnGuardar'
									},
									{
										xtype: 'button',
										text: 'Cancelar',
										icon: 'images/iconos/cancel.png',
										ref: '../../btnCancelar',
										style: 'margin-left:10px'
									}
								]
							}
                
            }
        ];
        formRentasDiasExtraWindowUi.superclass.initComponent.call(this);
    }
});
