/*
 * File: formRentasPagosWindow.js
 * Date: Sun Jun 11 2017 16:13:12 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

formRentasPagosWindow = Ext.extend(formRentasPagosWindowUi, {
	idReg: 0,
	id_pedido: 0,
	precio_renta: 0,
	inicializarEventos: function(){
		
		var dt = new Date();			
		this.txtFechaEntrega.setValue(dt);
		this.txtHoraEntrega.setValue(dt.format('H:i:s A'));		
		
		this.on('afterrender', function(){
			if(this.idReg > 0)
				this.getPago();
			else	
				this.getPedido();
		}, this);
		
		this.btnCancelar.on('click', function(){
			this.close();
		}, this);	

		this.btnGuardar.on('click', function(){
			this.guardar();
		}, this);			
		
	},
			
	initComponent: function() {
        formRentasPagosWindow.superclass.initComponent.call(this);
		this.inicializarEventos();
    },
	getPedido: function(){
		Ext.Ajax.request({
			url: "app.php/pedidos/getpedido",
			params: { id_pedido: this.id_pedido },
			scope:this,
			success: function(response){            
				var resp=eval ('('+response.responseText+")");
				
				this.txtPrecioRenta.setValue(resp.data.Pedido.precio_renta);				
				
			},
			failure: function(response){
				Ext.Msg.alert("Error en el servidor","No se recibieron los parámetros");            
			}
		});
	},
	getPago: function(){
		Ext.Ajax.request({
			url: "app.php/pedidos/getpago",
			params: { id_pago: this.idReg },
			scope:this,
			success: function(response){            
				var resp=eval ('('+response.responseText+")");
				this.txtFechaEntrega.setValue(resp.data.Pago.fecha_pago);
				this.txtHoraEntrega.setValue(resp.data.Pago.hora_pago);
				this.txtPrecioRenta.setValue(resp.data.Pago.importe);				
				
			},
			failure: function(response){
				Ext.Msg.alert("Error en el servidor","No se recibieron los parámetros");            
			}
		});
	},
	guardar:function(){
		if (this.formRentasPagosWindow.getForm().isValid()){			
			var params={};
			
			if(this.txtPrecioRenta.getValue()=="" || this.txtPrecioRenta.getValue() <= 0){
				Ext.Msg.alert('Aviso', 'Introduzca un importe valido.', function(){
					this.txtPrecioRenta.focus(false, true);
				}, this);
				return;
			}	

			var fecha = this.txtFechaEntrega.getValue();
			fecha=fecha.format('Y-m-d');  
			params['Pago[id_pago]'] = this.idReg;	
			params['Pago[id_pedido]'] = this.id_pedido;	
			params['Pago[fecha]'] = fecha;			
			params['Pago[hora]'] = this.txtHoraEntrega.getValue();			
			params['Pago[precio_renta]'] = this.txtPrecioRenta.getValue();			
						
			this.el.mask('Guardando...');
			this.formRentasPagosWindow.getForm().submit({
				params:params,
				scope:this,
				url:'app.php/pedidos/agregarpago',
				success:function(){
					this.el.unmask();
					//this.idReg=0;
					//this.formPedidos.getForm().reset();
					this.fireEvent("pagoGuardado");
					this.close();
					
				},
				failure:function(form, action){
					switch (action.failureType) {
		            case Ext.form.Action.CLIENT_INVALID:		                
		                msg="Favor de revisar los campos marcados";
		                icon=Ext.MessageBox.WARNING;
		                break;
		            case Ext.form.Action.CONNECT_FAILURE:		                
		                msg="Error en la comunicación ajax, intente de nuevo";
		                icon=Ext.MessageBox.ERROR;
		                break;
		            case Ext.form.Action.SERVER_INVALID:
		                icon=Ext.MessageBox.ERROR;
		                msg=action.result.msg;
					}
					Ext.Msg.show({
					   title:'Error',
					   msg: msg,
					   buttons: Ext.Msg.OK,						  						   
					   icon: icon
					});
					this.el.unmask();
					}

				});
				
			
		}else{
			return;
			
		}	
		
		
	}
});
Ext.reg('formRentasPagosWindow', formRentasPagosWindow);