/*
 * File: formRentasDiasExtraWindow.js
 * Date: Sun Jun 11 2017 16:13:12 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

formRentasDiasExtraWindow = Ext.extend(formRentasDiasExtraWindowUi, {
	idReg: 0,
	id_pedido: 0,
	dias_renta: 0,
	inicializarEventos: function(){
		
		var dt = new Date();					
		
		this.btnCancelar.on('click', function(){
			this.close();
		}, this);	

		this.btnGuardar.on('click', function(){
			this.guardar();
		}, this);			
		
	},
			
	initComponent: function() {
        formRentasDiasExtraWindow.superclass.initComponent.call(this);
		this.inicializarEventos();
    },	
	guardar:function(){
		if (this.formRentasDiasExtraWindow.getForm().isValid()){			
			var params={};
			
			if(this.txtDiasExtra.getValue()=="" || this.txtDiasExtra.getValue() <= 0){
				Ext.Msg.alert('Aviso', 'Introduzca un valor valido.', function(){
					this.txtDiasExtra.focus(false, true);
				}, this);
				return;
			}	
		  
			params['Pedido[id_pedido]'] = this.idReg;	
			params['Pedido[dias_extra]'] = this.txtDiasExtra.getValue();			
						
			this.el.mask('Guardando...');
			this.formRentasDiasExtraWindow.getForm().submit({
				params:params,
				scope:this,
				url:'app.php/pedidos/agregardiasextra',
				success:function(){
					this.el.unmask();
					
					this.fireEvent("diasGuardado");
					this.close();
					
				},
				failure:function(form, action){
					switch (action.failureType) {
		            case Ext.form.Action.CLIENT_INVALID:		                
		                msg="Favor de revisar los campos marcados";
		                icon=Ext.MessageBox.WARNING;
		                break;
		            case Ext.form.Action.CONNECT_FAILURE:		                
		                msg="Error en la comunicación ajax, intente de nuevo";
		                icon=Ext.MessageBox.ERROR;
		                break;
		            case Ext.form.Action.SERVER_INVALID:
		                icon=Ext.MessageBox.ERROR;
		                msg=action.result.msg;
					}
					Ext.Msg.show({
					   title:'Error',
					   msg: msg,
					   buttons: Ext.Msg.OK,						  						   
					   icon: icon
					});
					this.el.unmask();
					}

				});
				
			
		}else{
			return;
			
		}	
		
		
	}
});
Ext.reg('formRentasDiasExtraWindow', formRentasDiasExtraWindow);