/*
 * File: miErpWeb.storeGridRentasPagos.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('eNuevoOriente');
eNuevoOriente.storeGridRentasPagos = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        eNuevoOriente.storeGridRentasPagos.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeGridRentasPagos',
			idProperty: 'id_pago',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_pago'
                    
                },
				{
                    name: 'id_pedido'
                    
                },
				{
                    name: 'fecha_pago',
                    type: 'string'
                },
				{
                    name: 'hora_pago',
                    type: 'string'
                },
				{
                    name: 'id_cliente'
                    
                },
				
				{
                    name: 'nombre_cliente',
                    type: 'string'
                },
				{
                    name: 'importe',
                    type: 'string'
                },
				{
                    name: 'id_trabajador'
                    
                },
				{
                    name: 'nombre_trabajador',
                    type: 'string'
                }
				
			
			],
            url: 'app.php/pedidos/obtenerpagos'
        }, cfg));
    }
});
Ext.reg('storeGridRentasPagos', eNuevoOriente.storeGridRentasPagos);