/*
 * File: miErpWeb.storeGridRentasProductos.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('eNuevoOriente');
eNuevoOriente.storeGridRentasProductos = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        eNuevoOriente.storeGridRentasProductos.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeGridRentasProductos',
			autoDestroy: true,
			idProperty: 'id_producto',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_producto'
                    
                },
				{
                    name: 'id_asignacion'
                    
                },
				{
                    name: 'id_pedido'
                    
                },
				{
                    name: 'id_trabajador'
                    
                },
				{
                    name: 'descripcion',
                    type: 'string'
                },
				{
                    name: 'codigo_barra',
                    type: 'string'
                }
				
			
			],
            url: 'app.php/pedidos/obtenerproductosasignados'
        }, cfg));
    }
});
Ext.reg('storeGridRentasProductos', eNuevoOriente.storeGridRentasProductos);