/*
 * File: formPedidosWindow.ui.js
 * Date: Tue Dec 25 2018 23:34:27 GMT-0700 (Hora estándar Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

formPedidosWindowUi = Ext.extend(Ext.Window, {
    title: 'Pedido',
    width: 350,
    height: 460,
    modal: true,
    border: false,
    draggable: false,
    resizable: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
				itemId: 'formPedidosWindow',
				border: false,
				ref: 'formPedidosWindow',
				padding: 10,
				items: [
					{
						xtype: 'container',
						//flex: 1,
						layout: 'form',
						labelAlign: 'top',
						items: [
							{
								 xtype: 'combo',
								fieldLabel: 'Trabajador',
								width: 300,
								labelStyle: 'font-weight:bold;',
								allowBlank: false,
								forceSelection: true,
								hiddenName: 'id_trabajador',
								name: 'id_trabajador',
								displayField: 'nombre_trabajador',
								valueField: 'id_trabajador',
								enableKeyEvents: true,
								pageSize: 20,
								triggerAction: 'all',
								minChars: 2,
								
								ref: '../../cmbTrabajador'
							}
						]
					},
					{
						xtype: 'container',
						//flex: 1,
						layout: 'form',
						labelAlign: 'top',
						items: [
							{
								 xtype: 'combo',
								fieldLabel: 'Trabajador Ocacional',
								width: 300,
								labelStyle: 'font-weight:bold;',
								allowBlank: false,
								forceSelection: true,
								hiddenName: 'id_trabajador_ocacional',
								name: 'id_trabajador_ocacional',
								displayField: 'nombre_trabajador',
								valueField: 'id_trabajador',
								enableKeyEvents: true,
								pageSize: 20,
								triggerAction: 'all',
								minChars: 2,
								
								ref: '../../cmbTrabajadorOcacional'
							}
						]
					},
					{
						xtype: 'container',
						layout: 'hbox',
						items:[
							{
								xtype: 'container',
								layout: 'form',
								labelAlign: 'top',
								flex: 1,
								//width:100,
								items:[
									{
										xtype: 'datefield',
										fieldLabel: 'Fecha Entrega',
										itemId: 'txtFechaEntrega',
										name: 'fecha_entrega',
										width: 100,
										allowBlank: false,									
										ref: '../../../txtFechaEntrega'
									}
								]
							},
							{
								xtype: 'container',
								width: 20
							},
							{
								xtype: 'container',
								layout: 'form',
								labelAlign: 'top',
								//width:100,
								items: [									
									{
										xtype: 'timefield',
										fieldLabel: 'Hora Entrega',
										itemId: 'txtHoraEntrega',
										name: 'hora',
										width: 100,
										allowBlank: false,
										format: 'g:i:s A',
										labelStyle: 'font-weight:bold',												
										ref: '../../../txtHoraEntrega'
									}
								]
							}
						]
					},
					{
						xtype: 'container',
						layout: 'hbox',
						items:[
							{
								xtype: 'container',
								layout: 'form',
								labelAlign: 'top',
								flex: 1,
								items: [															
									{
										xtype: 'combo',
										fieldLabel: 'Plazo Pago',
										width: 100,
										labelStyle: 'font-weight:bold;',
										allowBlank: false,
										forceSelection: true,
										name: 'plazo_pago',
										displayField: 'nombre',
										valueField: 'id',
										mode: 'local',
										triggerAction: 'all',
										hiddenName: 'plazo_pago',
										editable: false,
										ref: '../../../txtPlazoPago'
									}
								]
							},
							{
								xtype: 'container',
								width: 20
							},
							{
								xtype: 'container',
								layout: 'form',
								labelAlign: 'top',
								//width:100,
								items: [															
									{
										xtype: 'datefield',
										fieldLabel: 'Fecha Ult. Venc.',
										itemId: 'txtFechaUltimoVencimiento',
										name: 'fecha_vencimiento',
										width: 100,
										disabled: true,
										labelStyle: 'font-weight:bold',												
										ref: '../../../txtFechaUltimoVencimiento'
									}
								]
							}
						]
					},
					{
						xtype: 'container',
						layout: 'hbox',
						items:[
							{
								xtype: 'container',
								layout: 'form',
								labelAlign: 'top',
								flex: 1,
								//width:100,
								items:[
									{
										xtype: 'numberfield',
										fieldLabel: 'Precio Renta',
										itemId: 'txtPrecioRenta',
										name: 'precio_renta',
										width: 100,
										allowNegative: false,
										submitValue: false,
										allowBlank: false,
										ref: '../../../txtPrecioRenta'
									}
								]
							},
							{
								xtype: 'container',
								width: 20
							},
							{
								xtype: 'container',
								layout: 'form',
								labelAlign: 'top',
								//width:100,
								items: [															
									{
										xtype: 'datefield',
										fieldLabel: 'Fecha Ult. Pago',
										itemId: 'txtFechaUltimoPago',
										name: 'fecha',
										width: 100,
										//allowBlank: false,
										labelStyle: 'font-weight:bold',												
										ref: '../../../txtFechaUltimoPago'
									}
								]
							}
						]
					},
					{
						xtype: 'container',
						//flex: 1,
						layout: 'form',
						labelAlign: 'top',
						items: [
							{
								xtype: 'textarea',
								fieldLabel: 'Observaciones',
								itemId: 'txtObservaciones',
								name: 'observaciones',
								width: 300,
								labelStyle: 'font-weight:bold',
								ref: '../../txtObservaciones'
							}
						]
					},
					{
						xtype: 'container',
						//flex: 1,
						layout: 'form',
						labelAlign: 'top',
						items: [
							{
								xtype: 'textfield',
								fieldLabel: 'Cliente',
								itemId: 'txtNombreCliente',
								name: 'nombre_cliente',
								width: 300,
								submitValue: false,
								disabled: true,
								ref: '../../txtNombreCliente'
							}
						]
					},
					
					
					
				],
				bbar: {
								xtype: 'toolbar',
								buttonAlign: 'right',
								items: [
									{
										xtype: 'button',
										text: 'Guardar',
										icon: 'images/iconos/save.png',
										itemId: 'btnGuardar',
										ref: '../../btnGuardar'
									},
									{
										xtype: 'button',
										text: 'Cancelar',
										icon: 'images/iconos/cancel.png',
										ref: '../../btnCancelar',
										style: 'margin-left:10px'
									}
								]
							}
                
            }
        ];
        formPedidosWindowUi.superclass.initComponent.call(this);
    }
});
