/*	
 * File: formPedidosWindow.js
 * Date: Sun Jun 11 2017 16:13:12 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

formPedidosWindow = Ext.extend(formPedidosWindowUi, {
	id_pedido: 0,
	inicializarEventos: function(){
		this.on('afterrender', function(){
			this.getPedido();
		}, this);
		
		this.btnCancelar.on('click', function(){
			this.close();
		}, this);	

		this.btnGuardar.on('click', function(){
			this.guardar();
		}, this);

		 var data=new Array(
							{id:'1',nombre:eNuevoOriente.formatearTexto('SEMANAL'),valor:'230.00'},
							{id:'2',nombre:eNuevoOriente.formatearTexto('1 DIA'),valor:'100.00'},
							{id:'3',nombre:eNuevoOriente.formatearTexto('2 DIAS'),valor:'150.00'},
							{id:'4',nombre:eNuevoOriente.formatearTexto('3 DIAS'),valor:'180.00'}
					);		
		this.txtPlazoPago.store.loadData({data:data}); 
		//this.cmbPlazoPago.setValue(1);
		
		this.txtPlazoPago.on('select',function(combo, record, index){
			var valor = record.get('valor');			
			this.txtPrecioRenta.setValue(valor);
			
		},this);	
		
	},
	inicializarStores: function(){
		
		this.txtPlazoPago.store = new eNuevoOriente.storeFormPedidosPlazoPagos();
		this.cmbTrabajador.store = new eNuevoOriente.storeFormPedidosTrabajadores();
		this.cmbTrabajador.store.load();	

		this.cmbTrabajadorOcacional.store = new eNuevoOriente.storeFormPedidosTrabajadores();
		this.cmbTrabajadorOcacional.store.load();		
	},		
	initComponent: function() {
        formPedidosWindow.superclass.initComponent.call(this);
		this.inicializarStores();
		this.inicializarEventos();
    },
	getPedido: function(){
		Ext.Ajax.request({
			url: "app.php/pedidos/getpedido",
			params: { id_pedido: this.id_pedido },
			scope:this,
			success: function(response){            
				var resp=eval ('('+response.responseText+")");
				
				// eNuevoOriente.UserConfig=resp.UserConfig;						
				
				this.cmbTrabajador.setValue(resp.data.Pedido.id_trabajador);
				this.cmbTrabajadorOcacional.setValue(resp.data.Pedido.id_trabajador_ocacional);
				this.txtFechaEntrega.setValue(resp.data.Pedido.fecha_entrega);
				this.txtHoraEntrega.setValue(resp.data.Pedido.hora_entrega);
				this.txtPrecioRenta.setValue(resp.data.Pedido.precio_renta);
				this.txtFechaUltimoVencimiento.setValue(resp.data.Pedido.fecha_ultimo_vencimiento);
				this.txtFechaUltimoPago.setValue(resp.data.Pedido.fecha_ultimo_pago);
				this.txtPlazoPago.setValue(resp.data.Pedido.plazo_pago);
				this.txtObservaciones.setValue(resp.data.Pedido.observaciones);
				this.txtNombreCliente.setValue(resp.data.Pedido.nombre_cliente);
				
			},
			failure: function(response){
				Ext.Msg.alert("Error en el servidor","No se recibieron los parámetros");            
			}
		});
	},
	guardar:function(){
		if (this.formPedidosWindow.getForm().isValid()){			
			var params={};		

			var fecha = this.txtFechaEntrega.getValue();
			fecha=fecha.format('Y-m-d');  
			params['Pedido[id_pedido]'] = this.id_pedido;	
			params['Pedido[fecha]'] = fecha;			
			params['Pedido[hora]'] = this.txtHoraEntrega.getValue();	
			params['Pedido[plazo_pago]'] = this.txtPlazoPago.getValue();		
			params['Pedido[precio_renta]'] = this.txtPrecioRenta.getValue();			
			params['Pedido[observaciones]'] = this.txtObservaciones.getValue();			
			params['Pedido[id_trabajador]'] = this.cmbTrabajador.getValue();
			params['Pedido[id_trabajador_ocacional]'] = this.cmbTrabajadorOcacional.getValue();
			var fechaUlt = this.txtFechaUltimoPago.getValue();
			fechaUlt=fechaUlt.format('Y-m-d');
			params['Pedido[fecha_ultimo_pago]'] = fechaUlt;						
			
			this.el.mask('Guardando...');
			this.formPedidosWindow.getForm().submit({
				params:params,
				scope:this,
				url:'app.php/pedidos/editar',
				success:function(){
					this.el.unmask();
					//this.idReg=0;
					//this.formPedidos.getForm().reset();
					this.fireEvent("pedidoGuardado");
					this.close();
					
				},
				failure:function(form, action){
					switch (action.failureType) {
		            case Ext.form.Action.CLIENT_INVALID:		                
		                msg="Favor de revisar los campos marcados";
		                icon=Ext.MessageBox.WARNING;
		                break;
		            case Ext.form.Action.CONNECT_FAILURE:		                
		                msg="Error en la comunicación ajax, intente de nuevo";
		                icon=Ext.MessageBox.ERROR;
		                break;
		            case Ext.form.Action.SERVER_INVALID:
		                icon=Ext.MessageBox.ERROR;
		                msg=action.result.msg;
					}
					Ext.Msg.show({
					   title:'Error',
					   msg: msg,
					   buttons: Ext.Msg.OK,						  						   
					   icon: icon
					});
					this.el.unmask();
					}

				});
				
			
		}else{
			return;
			
		}	
		
		
	}
});
Ext.reg('formPedidosWindow', formPedidosWindow);