/*
 * File: miErpWeb.storeGridPedidos.js
 * Date: Wed May 25 2011 16:58:59 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('eNuevoOriente');
eNuevoOriente.storeGridPedidos = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        eNuevoOriente.storeGridPedidos.superclass.constructor.call(this, Ext.apply({
            storeId: 'storeGridPedidos',
			idProperty: 'id_pedido',
			messageProperty: 'msg',
            root: 'data',
			totalProperty: 'totalRows',
            fields:[
				{
                    name: 'id_pedido'
                    
                },
				{
                    name: 'fecha_entrega',
                    type: 'string'
                },
				{
                    name: 'hora_entrega',
                    type: 'string'
                },
				{
                    name: 'id_cliente'
                    
                },
				
				{
                    name: 'nombre_cliente',
                    type: 'string'
                },
				{
                    name: 'calle',
                    type: 'string'
                },
				{
                    name: 'celular',
                    type: 'string'
                },
				{
                    name: 'precio_renta',
                    type: 'string'
                },
				{
                    name: 'observaciones',
                    type: 'string'
                },
				{
                    name: 'id_trabajador'
                    
                },
				{
                    name: 'id_trabajador_ocacional'
                    
                },
				{
                    name: 'nombre_trabajador',
                    type: 'string'
                },
				{
                    name: 'nombre_trabajador_ocacional',
                    type: 'string'
                },
				{
                    name: 'id_ruta'
                    
                },
				{
                    name: 'ruta',
                    type: 'string'
                },
				{
                    name: 'status',
                    type: 'string'
                },
				{
                    name: 'status_pedido',
                    type: 'string'
                },
				{
                    name: 'status_entrega',
                    type: 'string'
                },
				{
                    name: 'colonia',
                    type: 'string'
                },
				{
                    name: 'autorizada',
                    type: 'string'
                },
				{
                    name: 'origen',
                    type: 'string'
                }
			
			],
            url: 'app.php/pedidos/obtenerpedidos'
        }, cfg));
    }
});
Ext.reg('storeGridPedidos', eNuevoOriente.storeGridPedidos);